import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

// ✅ Precache static assets generated by Next.js
// This will be replaced by next-pwa at build time
// @ts-expect-error self.__WB_MANIFEST is injected by workbox at build time
precacheAndRoute(self.__WB_MANIFEST || []);

// ✅ Cache the main app page with NetworkFirst (offline-friendly)
registerRoute(
	({ url }) => url.pathname === '/' || url.pathname === '',
	new NetworkFirst({
		cacheName: 'app-shell-cache',
		plugins: [
			new CacheableResponsePlugin({ statuses: [0, 200] }),
			new ExpirationPlugin({
				maxEntries: 5,
				maxAgeSeconds: 60 * 60 * 24 * 7, // 1 week
			}),
		],
	})
);

// ✅ Runtime caching for prayers API with offline-first approach
registerRoute(
	({ url }) => url.pathname.startsWith('/api/prayers'),
	new CacheFirst({
		cacheName: 'prayers-cache',
		plugins: [
			new CacheableResponsePlugin({ statuses: [0, 200] }),
			new ExpirationPlugin({
				maxEntries: 50,
				maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
			}),
		],
	})
);

// ✅ Runtime caching for individual prayer slugs with offline-first
registerRoute(
	({ url }) => url.pathname.startsWith('/api/prayer/'),
	new CacheFirst({
		cacheName: 'prayer-detail-cache',
		plugins: [
			new CacheableResponsePlugin({ statuses: [0, 200] }),
			new ExpirationPlugin({
				maxEntries: 100,
				maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
			}),
		],
	})
);

// ✅ Example: Cache images with CacheFirst
registerRoute(
	({ request }) => request.destination === 'image',
	new CacheFirst({
		cacheName: 'image-cache',
		plugins: [
			new CacheableResponsePlugin({ statuses: [0, 200] }),
			new ExpirationPlugin({
				maxEntries: 100,
				maxAgeSeconds: 60 * 60 * 24 * 30,
			}), // 30 days
		],
	})
);

// ✅ Skip waiting and activate new SW immediately
self.addEventListener('install', () => {
	self.skipWaiting();
});
self.addEventListener('activate', (event) => {
	event.waitUntil(self.clients.claim());
});
